name: AppTidy
options:
  bundleIdPrefix: com.sryo
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  
  # Workaround for xcodegen not setting lastKnownFileType for icon.icon
  postGenCommand: sed -i '' 's|path = icon.icon; sourceTree = "<group>";|lastKnownFileType = folder.assetcatalog; path = icon.icon; sourceTree = "<group>";|' AppTidy.xcodeproj/project.pbxproj

targets:
  AppTidy:
    type: application
    platform: macOS
    sources:
      - path: AppTidy
      - path: icon.icon
        buildPhase: resources
        type: file
        lastKnownFileType: folder.assetcatalog
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sryo.AppTidy
      INFOPLIST_FILE: AppTidy/Info.plist
      ENABLE_HARDENED_RUNTIME: YES
      ENABLE_APP_SANDBOX: NO
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      SWIFT_VERSION: "5.9"
      ASSETCATALOG_COMPILER_APPICON_NAME: icon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      DEVELOPMENT_TEAM: "CL6XWJCS9R"
      CODE_SIGN_STYLE: "Manual"
      CODE_SIGN_IDENTITY: "A64B0EFEEF7B625D4595782B5BDF339A358B6E9D"
      PROVISIONING_PROFILE_SPECIFIER: ""
    dependencies: []
    info:
      path: AppTidy/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        CFBundleIconName: icon
        NSAppleEventsUsageDescription: "AppTidy needs access to control applications for undo functionality and Finder window tracking."
        NSAccessibilityUsageDescription: "AppTidy needs Accessibility permission to detect window states and manage app timeouts."
        NSPrincipalClass: NSApplication
