name: AppTidy
options:
  bundleIdPrefix: com.sryo
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  AppTidy:
    type: application
    platform: macOS
    sources:
      - path: AppTidy
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sryo.AppTidy
      INFOPLIST_FILE: AppTidy/Info.plist
      ENABLE_HARDENED_RUNTIME: YES
      ENABLE_APP_SANDBOX: NO
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      SWIFT_VERSION: "5.9"
    dependencies: []
    info:
      path: AppTidy/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSAppleEventsUsageDescription: "AppTidy needs access to control applications for undo functionality and Finder window tracking."
        NSAccessibilityUsageDescription: "AppTidy needs Accessibility permission to detect window states and manage app timeouts."
        NSPrincipalClass: NSApplication
